FROM python:3.11-slim as compile-image

ENV PYTHONUNBUFFERED=TRUE

RUN apt-get update && apt-get install -y gcc libffi-dev libsssl-dev libc6-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /kingdom

COPY requirements.txt /kingdom

RUN pip3 install --upgrade pip &&  pip3 install -r ./requirements.txt --no-cache-dir
RUN pip3 install gunicorn

FROM python:3.11-slim as build-image

ENV PYTHONUNBUFFERED=TRUE

WORKDIR /kingdom

RUN apt-get update && apt-get install -y gcc libffi-dev libsssl-dev libc6-dev && rm -rf /var/lib/apt/lists/*

COPY --from=compile-image /root/.local /root/.local

COPY ./ /kingdom

ENV PATH=/root/.local/bin:$PATH
